<?php
ob_start();
?>
    <div class="row">
        <div class="fullcolumn">
            <h2><?= $pageTitle ?></h2>
            <div class="container_form">
                <form id="addCategorie" action="" method="POST" class="form_post">
                    <?php include('./views/commons/_errors.phtml'); ?>
                    <?php include('./views/commons/_valids.phtml'); ?>
                    
                    <input class="input" type="text" name="category_name" id="category_name"  placeholder="Saisissez le nom de votre nouvelle catégorie" value="<?= isset($_POST['category_name']) ? $_POST['category_name'] : "" ?>"  required>
                    <div class="btnGroup">
                        <input type="submit" name="addPost" class="btnPost" value="Ajouter">
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php
$content = ob_get_clean();
require "views/commons/template.phtml";
?>


