<?php
ob_start();
?>      
    <div id="managePosts" style="margin-bottom:20px">  
        <?php if(empty($messages)) : ?>
            <p class="indispo">Aucun Message disponible</p>
        <?php else : ?>
            <table>
                <h1><?= $pageTitle ?></h1>

                <tr class="thead">
                    <th>Date</th>
                    <th>Auteur</th>
                    <th>Sujet</th>
                    <th>Contenue</th>
                    <th id="actions">Actions</th>
                </tr>
                <?php foreach ($messages as $message) : ?>
                    <tr>
                        <td><?= Tools::convertTimestampToFrenchDate($message['contact_date']) ?></td>
                        <td><?= htmlspecialchars($message['author']) ?></td>
                        <td><?= nl2br(substr($message['contact_subject'], 0,45 ) ). "..." ?></td>
                        <td><?= nl2br(substr($message['contact_content'], 0,45 ) ). "..." ?></td>
                        <td class="actions">
                            <a href="<?= URL.PAGE_VIEW_MESSAGE ?>/<?= $message['contact_id']?>" class="button eye" title ="voir le message"><i class="fas fa-eye"></i></a> 
                            <button class="button" title ="supprimer le message">
                            <a href="<?= URL.DELETE_MESSAGE ?>/<?= $message['contact_id'] ?>">
                            <i class="fas fa-trash"></i>
                            </a></button>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>
        <?php endif ?>
        <div class="btnGroup">
            <a href="<?= URL.PAGE_CONTACT ?>" class="btnAddPost">Voir le formulaire</a>
        </div>
    </div>
<?php
$content = ob_get_clean();
require "views/commons/template.phtml";
?>