<?php
ob_start();
?>      
    <div class="row">  
        <table>
            <h1 style="margin: 30px auto"><?= $pageTitle ?></h1>
            <?php if(empty($posts)) : ?>
                <p class="indispo">Aucun article disponible</p>
            <?php endif; ?>
            <tr class="thead">
                <th>Titre</th>
                <th>Date de d'ajout</th>
                <th>Auteur</th>
                <th>Contenue</th>
                <th>Categorie</th>
                <th id="actions">Actions</th>
            </tr>
            <?php foreach ($posts as $post) : ?>
                <tr>
                    <td><?= htmlspecialchars($post['post_title']) ?></td>
                    <td><?= Tools::convertTimestampToFrenchDate($post['post_created_date']) ?></td>
                    <td><a href="<?= URL ?><?= PAGE_COMPTE ?>/<?= htmlspecialchars($post['user_pseudo']) ?>"><?= htmlspecialchars($post['user_pseudo']) ?></a></td>
                    <td><?= nl2br(substr($post['post_content'], 0,45 ) )   . "..." ?></td>
                    <td><?= htmlspecialchars($post['category_name']) ?></td>
                    <td class="actions">
                        <a href="<?= URL.PAGE_EDIT_POST ?>/<?= htmlspecialchars($post['post_slug']) ?>" class="button edit" title ="modifier ce post"><i class="fas fa-edit"></i></a>  
                        <a href="<?= URL.PAGE_POST ?>/<?= htmlspecialchars($post['post_slug']) ?>" class="button eye" title ="voir ce post"><i class="fas fa-eye"></i></a> 
                        <button onclick="confirmDeletePost(<?= intval($post['post_id']) ?>)" class="button" title ="supprimer ce post"><i class="fas fa-trash"></i></button>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
        <div class="btnGroup tablePost" style="margin: 30px auto">
            <a href="<?= URL ?>ajoutPost" class="btnAddPost"><i class="fa-solid fa-plus"></i> <p>Article</p></a>
            <a href="<?= URL ?>ajoutCategorie" class="btnAddPost"><i class="fa-solid fa-plus"></i><p>Categorie</p></a>
        </div>
    </div>
<?php
$content = ob_get_clean();
require "views/commons/template.phtml";
?>