<?php
ob_start();
?>      
    <div id="managePosts">  
        <table>
            <h1><?= $pageTitle ?></h1>
            <?php if(empty($categories)) : ?>
                <p class="indispo">Aucune catégorie disponible</p>
            <?php endif; ?>
            <tr class="thead">
                <th>Nom</th>
                <th>Auteur</th>
                <th>Nb Articles</th>
                <th id="actions">Actions</th>
            </tr>
            <?php foreach ($categories as $categorie) : ?>
                <tr>
                    <td><?= htmlspecialchars($categorie['category_name']) ?></td>
                    <td><a href="<?= URL.PAGE_COMPTE ?>/<?= htmlspecialchars($categorie['author']) ?>"><?= htmlspecialchars($categorie['author']) ?></a></td>
                    <td><?= $categorie['post_count']?></td>
                    <td class="actions">
                        <a href="<?= URL.PAGE_CATEGORIES ?>/<?= htmlspecialchars($categorie['category_name']) ?>" class="button eye" title ="Voir les articles de cette catégorie"><i class="fas fa-eye"></i></a> 
                        <button onclick="confirmDeleteCategory(<?= $categorie['category_id']?>)" class="button" title ="supprimer cette catégorie"><i class="fas fa-trash"></i></button>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
        <div class="btnGroup">
            <a href="<?= URL.PAGE_AJOUT_POST ?>" class="btnAddPost"><i class="fa-solid fa-plus"></i> <p>Article</p></a>
            <a href="<?= URL.PAGE_AJOUT_CATEGORIE ?>" class="btnAddPost"><i class="fa-solid fa-plus"></i><p>Categorie</p></a>
        </div>
    </div>
<?php
$content = ob_get_clean();
require "views/commons/template.phtml";
?>