<?php
ob_start();
?>
  <div class="row">
      <div class="fullcolumn">
        <h1><?= $pageTitle ?></h1>
        <div class="container_form">
          <form id="addOrEditPost" action="" method="POST" enctype="multipart/form-data" >
            <?php include('./views/commons/_errors.phtml'); ?>
            <?php include('./views/commons/_valids.phtml'); ?>

            <div class="inputDiv">
              <label for="postTitle">Titre</label>
              <input type="text" name="post_title" id="post_title" data-infos="infosPostTitle"  placeholder="Ajouter un nouveau titre" value="<?= htmlspecialchars($post['post_title']);  ?>"  required>
              <span class="infosPostTitle spanInfos"></span>    
            </div>

            <div class="inputDiv">
              <label for="postCategory">Catégorie</label><br>
              <div class="custom-select">
                <select name="post_category" class="form-control" id="post_category"  required>
                  <?php foreach($categories as $cat): ?>
                    <option value="<?= intval($cat['category_id']) ?>" <?php if( intval($cat['category_id']) === intval($post['post_category'])){echo "selected"; } ?>> <?= htmlspecialchars($cat['category_name']) ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
            </div>


            <div class="inputPostImag">
              <label for="post_image">Image : </label>
              <div class="upload-btn-wrapper">
                <button class="btnUpload">Choisir </button>
                <input type="file" name="post_image" accept="image/*" onchange="previewImage(event)" />
              </div>
            </div>

            <div class="viewImg">
              <img id="output_image"/>
              <img src="<?= URL ?>public/images/imgPost/<?= $post['post_image'] ?>" class="img_art" alt="image">
            </div>

            <textarea name="post_content" id="countC" data-infos="infosPostContent"  class="form-control" required><?= html_entity_decode($post['post_content']);  ?></textarea> 
            <span class="infosPostContent spanInfos"></span>    
              
            <div class="btnGroup">
              <input class="btnPost" type="submit" name="editPost" class="" value="Modifier">
            </div>

          </form>
        </div>
      </div>
  </div>
<?php
$scripts = '<script src="'.URL.'public/js/post.min.js"></script>';
$content = ob_get_clean();
require "views/commons/template.phtml";
?>


