<?php
ob_start();
?>

    <div class="row">
        <div class="leftcolumn">
            <div class="card-article" data-id ="<?= $post['post_id'] ?>">
                <h2 class="title"><?= $pageTitle ?></h2>
                <div class="card-img">
                    <img src="<?= URL ?>public/images/imgPost/<?= $post['post_image'] ?>" class="img_art" alt="image">
                </div>
                <div class="infosArticle">
                    <a href="<?= URL ?><?= PAGE_COMPTE ?>/<?= htmlspecialchars($post['user_pseudo']) ?>" class="infoAuthor" > 
                        <i class="fa-solid fa-user-pen" ></i>
                        <span><?= htmlspecialchars($post['user_pseudo']) ?></span>
                    </a>
                    <p class="infoDate">
                        <i class="fa-solid fa-calendar-days"></i>
                        <span><?= Tools::convertTimestampToFrenchDate($post['post_created_date']) ?></span>
                    </p>
                </div>

                <div class="content"><?= nl2br($post['post_content']) ?></div>
                           
                <div class="card-footer">
                    <p class="back"><a href="javascript:history.back()" class="text-white"><span>Retour</span></a></p> 
                    <p class="fin">FIN.</p>
                </div>

                <div class="" id="listComments"></div>

                <form method="POST"  action="" id="commentForm" onsubmit ="submitComment(event)">

                    <legend> 
                        <i class="fa-solid fa-comments"></i>
                        <span>Laisser un commentaire</span>
                    </legend>
                    <p class="text-center"> 
                        <span id="spanInfos">
                            Seul les membres connectés peuvent laisser un commentaire
                        </span>
                    </p>
                    <div class="errorComment"></div>
                    <div class="successComment"></div>
                    <label> Commentaire :</label>
                    <input type="text" name="idPost" value="<?= intval($post['post_id']) ?>" hidden>
                                            
                    <textarea id="comment_content" data-infos="infosComment"  name="comment_content" placeholder="Ecrivez un commentaire..."  ><?= (isset($post['comment_content'])) ? htmlspecialchars($post['comment_content']) : ""  ?></textarea>
                    <span class="infosComment spanInfos"></span>    

                    <input class="btnComment" type="submit" name="commentPost" value="Commenter">
                </form>
                <p class="infosComment"></p>

            </div>
          
        </div>
      
        <div class="rightcolumn">
            <div class="card">
                <?php include("views/commons/_searchBar.phtml"); ?>
            </div>
            
            <div class="card">
                <?php include("views/commons/_categories.phtml"); ?>
            </div>

            <div class="card">
                <?php include("views/commons/_recentPosts.phtml"); ?>
            </div>
        </div>
        
    </div>
<?php
$scripts = '
<script src="'.URL.'public/js/comment.min.js"></script>
<script src="'.URL.'public/js/searchPosts.min.js"></script>';
$content = ob_get_clean();
require "views/commons/template.phtml";
?>



