<?php
ob_start();
?>
<body>  
    <div class="compte">

        <div class="left">
    
            <h2 class="text-white">Mon Compte</h2>
            <img class="img_profil roundImg" src="public/images/avatars/<?= $user['user_avatar']?>" alt="">

            <p class ="name" ><?= htmlspecialchars($user['user_firstname']) ?> <?= htmlspecialchars($user['user_lastname']) ?> </p>

            <a href="<?= URL ?>monCompte#infosCompte"  class="button infos" title="Voir les informations de mon compte">Informations du compte</a>
            <a href="<?= URL ?>editCompte#editInfos" class="button success" title="Modifier les informations de mon compte">Modifier mes informations</a>
            <a href="<?= URL ?>deconnexion" class="button danger" title="Me déconnecter">Déconnexion</a>
        </div>
        
        <div class="right">

            <?php if($_GET['page'] == PAGE_EDIT_COMPTE) : ?>
        
                <div class="sectionContent">
                    <form  id="editInfos" enctype="multipart/form-data" action="" method="POST">
                        <h2><?= $pageTitle ?></h2>
                        <p class="infoForms">Une fois la modification effectué vous serez déconnecté</p>

                        <span class="text-center">Cliquez <a href="<?= URL ?>editAvatar#editAvatar">ici</a> pour changer d'avatar</span>
                        <?php include('./views/commons/_errors.phtml'); ?>
                        <?php include('./views/commons/_valids.phtml'); ?>
                        
                        <div class="inputDiv">
                            <input class="input" type="password" name="user_password" placeholder="Mot de passe actuel" value="<?= $data['actualPassword'] ?>">
                        </div>
                        
                        <div class="inputDiv inputPassword">
                            <input type="password" name="newPassword" class="input" onfocus="verifFormatPassword()" id="newPassword" value="<?= $data['newPassword'] ?>" placeholder="Nouveau Mot de passe">
                            <div id="messageBox">
                                <p id="letter" class="invalid">Une <b>lettre minuscule</b> </p>
                                <p id="capital" class="invalid">Une <b>lettre majuscule</b></p>
                                <p id="number" class="invalid">Un <b>Chiffre</b></p>
                                <p id="length" class="invalid">Minimum <b>5 caractères</b></p>
                            </div>
                        </div>
                        
                        <div class="inputDiv inputPassword">
                            <input type="password"  name="newPasswordConfirm" class="input" onfocus="verifFormatPasswordConfirm()" id="newPasswordConfirm" value="<?= $data['newPasswordConfirm'] ?>"  placeholder="Confirmez votre nouveau mot de passe">
                            <p id="conform" class="invalid"> Mot de passe identique</p>
                        </div>

                        <div class="btnGroup">
                            <button class="btn-editInfos" type="submit" title="Valider les modifications" >Valider</button>
                        </div>
                    </form>
                </div>

            <?php elseif($_GET['page'] == PAGE_MON_COMPTE) :  ?>

                <div id="infosCompte">

                    <h2>Mes Informations</h2>

                    <div class="infos text-center">
                        <p>Email : <?= htmlspecialchars($_SESSION['email']) ?>  </p>
                        <p>Inscrit depuis le <?= Tools::convertTimestampToFrenchDate($user['user_date_create']) ?></p>
                        <p>Dernière connexion : <?= Tools::convertTimestampToFrenchDate($user['user_last_connexion']) ?></p>

                        <a href="javascript:void(0);" title="supprimer mon compte" class="button danger" onclick="confirmDeleteUser(<?= intval($_SESSION['id']) ?>)">Supprimer mon compte</a>
                    </div>
                </div>

            <?php elseif($_GET['page'] == PAGE_EDIT_AVATAR) : ?>   

                <div id="editAvatar" class="sectionContent">
                    <form class="editInfos" id="editInfos" enctype="multipart/form-data" action="" method="POST">
                        <h2><?= $pageTitle ?></h2>
                        <?php include('./views/commons/_errors.phtml'); ?>
                        <?php include('./views/commons/_valids.phtml'); ?>
                    
                            <div class="image-upload">
                                <label for="file-input">
                                   <div class="containerUpload">
                                      <img src="public/images/avatars/<?= $user['user_avatar']?>" alt="Avatar" class="avatarUser">
                                      <div class="middle">
                                        <div class="iconCamera"><i class="fa-solid fa-camera"></i></div>
                                      </div>
                                    </div>
                                </label>
                                
                              <input name="user_avatar"  id="file-input" type="file" hidden onchange="previewImage(event)"   />
                            </div>

                            <p class="text-center">Votre nouvel avatar apparaîtra en dessous</p>
                            <img id="output_image" />

                        </div>
                        <div class="btnGroup">
                            <input name="changeAvatar" class="btn-changeAvatar" type="submit" title="Changer d'avatar" value = "Changer" >
                        </div>
                    </form>
                </div> 
            <?php endif; ?>
        </div>
    </div>

<?php
$scripts = '<script src="'.URL.'public/js/account.min.js"></script>';
$content = ob_get_clean();
require "views/commons/template.phtml";
?>



