<?php
ob_start();
?>
    <div class="compte">

        <div class="left">
            <img class="img_profil" src="<?= URL ?>/public/images/avatars/<?= $user['user_avatar']?>" alt="">

            <p class ="name"><?= Tools::concatPrenomNom($user['user_firstname'],$user['user_lastname']); ?> </p>
            <a href="" class="button infos" title=""><i class="fa-solid fa-user-plus"></i><span>Ajouter</span></a>
            <a href="" class="button success" title=""><i class="fa-regular fa-comment"></i><span>Message</span></a>
        </div>
        
        <div class="right">

            <div id="infosCompte">

                <div div class="infos text-center">
                    <p>Inscrit depuis le <?= Tools::convertTimestampToFrenchDate($user['user_date_create']) ?></p>
                    <p>Dernière connexion : <?= Tools::convertTimestampToFrenchDate($user['user_last_connexion']) ?></p>

                    <div>
                        <?= Tools::concatPrenomNom($user['user_firstname'],$user['user_lastname']); ?>
                        a publié <?= $nbArticles; ?> article(s) :

                         <?php foreach($postOfUser as $post) : ?>
                            <span><a href="<?= URL.PAGE_POST ?>/<?= $post['post_slug']; ?>"><?= htmlspecialchars($post['post_title']) .", " ?></a></span>
                        <?php endforeach; ?> 

                    </div>
                </div>
            </div>
        </div>

    </div>
<?php
$scripts = '<script src="'.URL.'public/js/account.min.js"></script>';
$content = ob_get_clean();
require "views/commons/template.phtml";
?>



