<?php
ob_start();
?>
    <style>
        .btn.addFriend{
            background-color: #0062CC;
            border: none;
            color: white;
            font-size: 2.5rem;
            margin: 5px;
            text-align: center;
            padding: 11px;
            border-radius: 20px;
            cursor: pointer;
            width: 260px;
        }

        .left > a {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .left > a i {
            margin-right: 10px;
        }
    </style>

    <div class="compte">

        <div class="left">
            <img class="img_profil" src="<?= URL ?>/public/images/avatars/<?= $user['user_avatar']?>" alt="">

            <p style="font-size:3rem"><?= htmlspecialchars($user['user_firstname']) ?> <?= htmlspecialchars($user['user_lastname']) ?> </p>
            <a href="" class="button infos" title="Voir les informations de mon compte"><i class="fa-solid fa-user-plus"></i><span>Ajouter</span></a>
            <a href="" class="button success" title="Envoyez lui un message"><i class="fa-regular fa-comment"></i><span>Message</span></a>
        </div>
        
        <div class="right">

            <div id="infosCompte">

                <div div class="infos text-center">
                    <p>Inscrit depuis le <?= Tools::convertTimestampToFrenchDate($user['user_date_create']) ?></p>
                    <p>Dernière connexion : <?= Tools::convertTimestampToFrenchDate($user['user_last_connexion']) ?></p>

                    <div>
                        <?= Tools::concatPrenomNom($user['user_firstname'],$user['user_lastname']); ?>
                        a publié <?= $nbArticles; ?> article(s) :

                         <?php foreach($postOfUser as $post) : ?>
                            <span><a href="<?= URL.PAGE_POST ?>/<?= $post['post_slug']; ?>"><?= htmlspecialchars($post['post_title']) .", " ?></a></span>
                        <?php endforeach; ?> 

                    </div>
                </div>
            </div>
        </div>

    </div>
<?php
$scripts = '<script src="'.URL.'public/js/account.min.js"></script>';
$content = ob_get_clean();
require "views/commons/template.phtml";
?>



