<?php if(isset($_SESSION['message']) && !empty($_SESSION['message'])) : ?>

  <div id="myModal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <p class="modal-content-msg"><?= $_SESSION['message'] ?></p>
    </div>
  </div>

  <script>
    const modal = document.querySelector("#myModal");
    const span = document.querySelector(".close");
    
    span.addEventListener("click", function() {
      modal.style.display = "none";
    });
    
    window.addEventListener("click", function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    });
  </script>
<?php endif; ?>
<?php unset($_SESSION['message']); ?>

